### PR TITLE
Add skill name under icons in SoftwareSkills

### PR DESCRIPTION
**Pull request by AmnaEjaz**

### CODE REVIEW

**Comment by saadpasta** [comment]
@AmnaEjaz Please update the title and description. 
And can you please change color of the text on hover.

**Comment by kartik918** [comment]
I changed the title to help you out since I see this is your first time contributing here. 

Also @saadpasta skillnames are used to get `fa` icons so they won't be capitalized, should we encourage users to do it or use `string.charAt(0).toUpperCase()` to do it automatically?

**Comment by saadpasta** [comment]
@kartik918 we are using **fontAwesomeClassname** for font awesome icons. 
I guess there is no need to capitalize as users can do it from its own.

**Comment by kartik918** [comment]
Oh, thanks! I didn't remember we weren't using `skillName` prop anywhere and thought that was used for FA class names.

**Comment by AmnaEjaz** [comment]
> @AmnaEjaz Please update the title and description of your PR
> And can you please change color of the text on hover.

Alright

**Comment by saadpasta** [comment]
@allcontributors please add @AmnaEjaz for code and idea

**Pull request merged**
