### PR TITLE
Dark Mode Slider Fix with Security Fixes

### PR DESCRIPTION
**Pull request by WarenGonzaga**
This is my commit to fix the security vulnerabilities.

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
@saadpasta is this normal?

**Comment by WarenGonzaga** [comment]
Fix for #263 deployed... @saadpasta

**Comment by WarenGonzaga** [comment]
@kartikcho can you review it?

**Review by kartikcho — APPROVED** [review]
The patch looks good, I tried it on the deployed version myself (have to kickstart the Vercel deployments manually for some reason, I'll look into a better alternative maybe).

Anyway, we might have to hold off on merging this one for a bit, as it updates a package and the generated package-lock.json. We have a backlog of PRs to get in first, #138 #260 and #259.
Great work, thanks!

**Comment by WarenGonzaga** [comment]
Awesome @kartikcho ;) I have some projects within this repo can you check it also and assigned it to me?

**Comment by saadpasta** [comment]
@WarenGonzaga please resolve conflicts. So we can merge this. ✌️

**Comment by WarenGonzaga** [comment]
@saadpasta sure thing let me fix this

**Comment by WarenGonzaga** [comment]
Done @saadpasta

**Review by saadpasta — APPROVED** [review]

**Comment by saadpasta** [comment]
@allcontributors please add @WarenGonzaga for code

**Pull request merged**
