### PR TITLE
Adds new component for resume abstraction

### LINKED ISSUE #40: Add appropriate href in contact
- Add `tel:` and `mailto:` hrefs for contact section.

### LINKED ISSUE #41: Resume URL abstraction
- Create a new _Resume_ component with iframe src as the drive link for the file, so that it looks cleaner instead of redirecting to Google Drive.

### PR DESCRIPTION
**Pull request by rajkumaar23**
- Fixes #41 

Screenshots :
image

### CODE REVIEW

**Comment by rajkumaar23** [comment]
@saadpasta Kindly look into this PR and suggest changes if any :)

**Comment by rajkumaar23** [comment]
@saadpasta Kindly look into this PR and suggest changes if any :)

**Comment by saadpasta** [comment]
@rajkumaar23 please make 2 separate merge request for href and new resume component so we have a better idea

**Comment by saadpasta** [comment]
@kartik918 what do you think about new resume component

**Comment by rajkumaar23** [comment]
> @rajkumaar23 please make 2 separate merge request for href and new resume component so we have a better idea

I have made two separate 2 PRs. Please check the other one at #44

**Comment by rajkumaar23** [comment]
> Please remove .gitignore, package-lock.json and package.json from your pull request. I guess they are not needed for this Merge Request

- I have added `react-router` for routing, because of which I've committed package files.
- And the .gitignore misses a folder(**.idea/**) that's usually configuration files when you work on Jetbrains IDEs.

**Comment by rajkumaar23** [comment]
@kartik918 Can you please review this too ?

**Comment by kartik918** [comment]
This feature is a good one. 
Can you provide more descriptive screenshots/gif showing redirecting being changed? 
@rajkumaar23

**Comment by rajkumaar23** [comment]
> This feature is a good one.
> Can you provide more descriptive screenshots/gif showing redirecting being changed?
> @rajkumaar23

dev

**Comment by rajkumaar23** [comment]
> Great work implementing react router for seamless links.

Thanks! But there's a problem. `gh-pages` by default doesn't support SPA and hence when an user visits our application directly at `http://domain.com/resume`, `gh-pages` or any other server will throw **404**.
There are two hacks to avoid this : 
1) On a VPS, a .htaccess file would solve this.
2) On gh-pages, we'll have to parse the URL from our 404.html and then send it back to our application's root with the URL as a parameter and now we can redirect to the desired `/resume`.

So my question is should this information be mentioned in the README.md ?

**Comment by kartik918** [comment]
``.htaccess`` redirection  would reduce load speed of the resume component I think

**Comment by kartik918** [comment]
Since we'll be building on gh pages, we cannot use react router as GitHub has a protected server.

Redirecting 404 is a bad hack to use.

If you can design a solution with ``.htaccess`` , that would be better.

**Comment by rajkumaar23** [comment]
.htaccess can only be used when you have a private server and not on 
`gh-pages`. Also, this isn't a bug. Internal navigation will still work 
good.

**Comment by rajkumaar23** [comment]
> Since we'll be building on gh pages, we cannot use react router as GitHub has a protected server.
> 
> Redirecting 404 is a bad hack to use.
> 
> If you can design a solution with `.htaccess` , that would be better.

.htaccess can only be used when you have a private server and not on
`gh-pages`. Also, this isn't a bug. Internal navigation will work as intended rhrough react-router, when hosted with ghpages. 
For example, you can check the resume link at https://rajkumaar.co.in ( built with React and hosted by gh-pages) :)

**Comment by saadpasta** [comment]
@rajkumaar23 I guess parsing the URL from our 404.html and then redirect it the resume page is the only hack we can do and I guess you have done it in the same way in your portfolio. 

@kartik918 what do you say because if we want this feature we have to do this hack to avoid the 404 page

**Comment by rajkumaar23** [comment]
> @rajkumaar23 I guess parsing the URL from our 404.html and then redirect it the resume page is the only hack we can do and I guess you have done it in the same way in your portfolio.
> 
> @kartik918 what do you say because if we want this feature we have to do this hack to avoid the 404 page
I don't think redirection is required, because it's less frequent that the direct URL is hit. Hence, we can leave it to the user to follow the 404 hack or not. We can, may be, add a note on this in the README.md

**Comment by rajkumaar23** [comment]
It is anyways mentioned [here](https://create-react-app.dev/docs/deployment/#notes-on-client-side-routing) (the page which you've mentioned in the deployment section of README.md

**Comment by saadpasta** [comment]
@rajkumaar23 I guess you are right it's less frequent but I guess if someone will copy the URL and send it someone so he can view his CV/Resume then it leaves a bad impression.
We have to do the redirection hack I guess. if you could implement that it would be great.

**Comment by rajkumaar23** [comment]
> @rajkumaar23 I guess you are right it's less frequent but I guess if someone will copy the URL and send it someone so he can view his CV/Resume then it leaves a bad impression.
> We have to do the redirection hack I guess. if you could implement that it would be great.

Sure I can. But the `404.html` has to be from the user's side. It won't be generated in the build dir.

**Comment by rajkumaar23** [comment]
@saadpasta Do you want me to add `.htaccess` too ? For those who would love deploying on their own servers ?

**Comment by kartik918** [comment]
@saadpasta In the end it's weighing if the feature is worth the redirection and addition of react-router dependencies just to have seamless link to resume. 
It's your decision, I'm not for it.

**Comment by rajkumaar23** [comment]
> @saadpasta In the end it's weighing if the feature is worth the redirection and addition of react-router dependencies just to have seamless link to resume.
> It's your decision, I'm not for it.

I feel it looks professional when the resume loads up within your page, than from GDrive :)

**Comment by kartik918** [comment]
> I feel it looks professional when the resume loads up within your page, than from GDrive :)

Redirecting 404 to serve our purpose isn't exactly professional practice in my opinion.

**Comment by rajkumaar23** [comment]
> > I feel it looks professional when the resume loads up within your page, than from GDrive :)
> 
> Redirecting 404 to serve our purpose isn't exactly professional practice in my opinion.

Unfortunately, that's how SPAs work if **not** hosted on private servers :(

**Comment by saadpasta** [comment]
> @saadpasta In the end it's weighing if the feature is worth the redirection and addition of react-router dependencies just to have seamless link to resume.
> It's your decision, I'm not for it.

@kartik918 I also think adding dependencies and a hack just for resume is not a good option and we will only add new features if we both agree on it. 
@rajkumaar23 let's keep this feature for the future 
Thanks for your contribution ❤️

**Pull request closed without merging**
