### PR TITLE
Updated outward button transition

### PR DESCRIPTION
**Pull request by sparsh-99**
#156 
#### New Features:-
- Added the animations in the .main-button and .main-button:hover class.

### CODE REVIEW

**Comment by sparsh-99** [comment]
Revert changes in package-lock.json and did 3 changes in Button.css file in commit `39dbad`. 
Hope now, it will be good enough to be merged @saadpasta

**Comment by sparsh-99** [comment]
Hey @saadpasta, Can you please add me to your contributor's list. It will be great.

**Comment by saadpasta** [comment]
@allcontributos please add @sparsh-99 for code

**Comment by saadpasta** [comment]
@allcontributors please add @sparsh-99 for code

**Pull request merged**
