### PR TITLE
added preloader

### PR DESCRIPTION
**Pull request by AbhipsaGuru1012**
Fixes: #357 

preloader

### CODE REVIEW

**Comment by kartikcho** [comment]
Hey, I meant working on #365 and #366's changes to instead of working on a new branch and opening another PR. This is also different from what was discussed in #357.
If the existing PRs don't see any activity for a while, we can get this in instead.

**Comment by AbhipsaGuru1012** [comment]
> Hey, I meant working on #365 and #366's changes to instead of working on a new branch and opening another PR. This is also different from what was discussed in #357.
> If the existing PRs don't see any activity for a while, we can get this in instead.

@kartikcho oh okay. So are the changes made in this PR okay or should I try working on the existing PRs?

**Comment by kartikcho** [comment]
You can read those PRs to get more context on what is left to be done and pick it up from there. Feel free to ask questions in those PRs if you're confused about anything.

You can leave this open for now if we need to come back to it.

**Comment by kartikcho** [comment]
You only need to rebase the PR for 365 but I'll do it. Also, this PR uses CSS loader instead of a lottie animation which was decided upon in the issue so we might not get this in.

**Comment by saadpasta** [comment]
@kartikcho do we need to close this or @AbhipsaGuru1012 will you replace the loader with lottie.

**Comment by kartikcho** [comment]
We can close this, #365 has been merged and #366 will add these changes with a lottie loader. @AbhipsaGuru1012 can follow up on it's work (if they want to) or I'll do it myself later.

**Pull request closed without merging**
