### PR TITLE
Fix extra space when contactInfo.number is not given in Contact Section

### PR DESCRIPTION
**Pull request by RedHeadphone**

### CODE REVIEW

**Review by sadapasta — APPROVED** [review]

**Review by saadpasta — APPROVED** [review]

**Comment by RedHeadphone** [comment]
@saadpasta can I add myself as Contributors in the README.md ? Also is it possible that I can get hacktoberfest accepted tag in the PR ?

**Comment by saadpasta** [comment]
Sorry I am adding you to contributors

**Comment by saadpasta** [comment]
@allcontributors please @RedHeadphone for code

**Comment by saadpasta** [comment]
@allcontributors please add @RedHeadphone for code

**Pull request merged**
