### PR TITLE
Some changes to twitter component

### PR DESCRIPTION
**Pull request by naveen521kk**
I have done some changes to twitter component to make it look fine with other elements. I have made it transparent and removed the default header and added a new one. Check out the screenshot below.
tweets
Further, I did an edit changes talks from upper case to lower case.

### CODE REVIEW

**Comment by kartik918** [comment]
Can you send screenshot of what changed?

**Comment by naveen521kk** [comment]
This is the old one.
tweet1
This the new one.
tweets

**Comment by naveen521kk** [comment]
And this PR is to help #92 .

**Comment by kartik918** [comment]
I think the original header looks better and more fluent. What do you think @saadpasta ?

**Comment by saadpasta** [comment]
> I think the original header looks better and more fluent. What do you think @saadpasta ?

@kartik918 I also think so. We could also make the component little small.

**Comment by naveen521kk** [comment]
> 
> 
> I think the original header looks better and more fluent. What do you think @saadpasta ?

@kartik918 The original headers are not aligned with other components. So I had to change it. Further, I made the component transparent for the dark mode to work well.

**Comment by kartik918** [comment]
> @kartik918 The original headers are not aligned with other components. So I had to change it. Further, I made the component transparent for the dark mode to work well.

Since the only thing we need out of this PR is the transparent bg, I think @MohammadHasham can accommodate for it in his PR. 
We'll reopen this when it is required. 
Thanks!

**Pull request closed without merging**
