### PR TITLE
Add carousel slider in work experience and achievement section

### PR DESCRIPTION
**Pull request by skgupta77159**
Hi, See I have added a carousel slider in the work experience and Achievement & certificate section. so that more experience and certificates can be added without just increasing the length of the portfolio. I found that if we add more achievements, the cards are increasing on the same page instead slider can do better for adding more than cards.

### CODE REVIEW

**Review by kartikcho — CHANGES_REQUESTED** [review]
Thanks for opening this PR, this is a neat change that would make our existing components even better!

Took a brief look at the changes:

- Since our use case isn't complex, we can/should avoid adding a big package like `react-elastic-carousel` for adding a simple carousel. We could maybe implement our own carousel.
- There is no CSS styling for carousel buttons and carousel 'page' indicators in dark mode.
- ~The left button 'icon' is a bit off center, I think it might be a problem with the symbol and not with CSS.~ Edit: Looking at it again, it seems normal so you may discard this. 

image

- By default we don't need to keep dummy cards to show the carousel, we could add it in our docs that the components are flexible to hold multiple cards.
- Not sure how flexible the component is but the disabled icon on left (for scrolling to content that doesn't exist) looks ugly. We could either hide the button altogether in that case or set it to infinite scroll.

Let me know if you need any help or want a bit more clarification on my ideas.

**Comment by kartikcho** [comment]
Hey @skgupta77159 are you still working on this?

**Comment by saadpasta** [comment]
@kartikcho should we close this one also

**Comment by kartikcho** [comment]
@saadpasta it looks like a good addition (maybe not the best implementation). We can either keep this open or make a new issue linking to this for reference because the portfolio should handle cases like having too many achievement cards without breaking or cluttering layout.

**Comment by sadapasta** [comment]
@kartikcho I create a an issue linking to this PR

**Comment by saadpasta** [comment]
@kartikcho I create a an issue linking to this PR

**Pull request closed without merging**
