### PR TITLE
Hot Fix : Fix Spelling Error in achievementsCards.js

### LINKED ISSUE #267: Production Crashing due to spelling mistake in Achievement Card
**Describe the bug**
Production Crashing due to spelling mistake in Achievement Card

**To Reproduce**
1. Go to 'developerFolio.js.org'
2. Open Console 

**Is this responsiveness Issue**
NO

**Screenshots**
Capture213

### PR DESCRIPTION
**Pull request by saadpasta**
Fixes #267

### CODE REVIEW

**Comment by saadpasta** [comment]
@kartikcho @naveen521kk @MuhammadHasham23.
Please make sure to check production URL (`developerFolio.js.org`) after merging the PR.

**Comment by naveen521kk** [comment]
It would be good if you could give us the authorisation to deploy on vercel .(this could have been avoided).

**Comment by saadpasta** [comment]
@naveen521kk Sure. Please provide me with your email address I add them to vercel.

**Comment by saadpasta** [comment]
@naveen521kk I guess you need to have a PRO account to invite team member. I just a 14 days trail.

**Comment by naveen521kk** [comment]
>  Please provide me with your email address I add them to vercel.

It's in my profile.

> I guess you need to have a PRO account to invite team member. I just got a 14 days trail.

I though vercel team was free for OS projects? I don't know though.

**Comment by saadpasta** [comment]
@saadpasta I think we need to do something else `Environment Variables` are causing the issue and that's why they required my authorization

**Comment by kartikcho** [comment]
@saadpasta if we're having trouble with Vercel we should definitely look into other options like Netlify to do the job, because preview deploys are pretty essential for reviews.

**Comment by saadpasta** [comment]
@kartikcho I'll look into Netlify integration

**Pull request merged**
