### PR TITLE
Fix: Resume button in nav bar

### PR DESCRIPTION
**Pull request by Jolomi-Tosanwumi**
# Description

Fixed: Resume button in nav bar not redirecting to "DOWNLOAD MY RESUME" button.

Fixes  (#737)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by Jolomi-Tosanwumi** [comment]
Added empty div before "DOWNLOAD MY RESUME" button to make the resume nav properly redirected to the the button regardless if the current viewport is before the "DOWNLOAD MY RESUME" button or after it.

**Comment by saadpasta** [comment]
Thanks for contributing @Jolomi-Tosanwumi

**Review by saadpasta — APPROVED** [review]

**Comment by Jolomi-Tosanwumi** [comment]
Thank you @saadpasta. Please don't forget to add me as a contributor :)

**Comment by Jolomi-Tosanwumi** [comment]
Hi @saadpasta, @kartikcho . Reminder to add me as a contributor :)

**Comment by Albert1024-dev** [comment]
hi

**Pull request merged**
