### PR TITLE
fix: email address key retrieve properly

### LINKED ISSUE #294: ContactInfo Section is not loading the title,number or email address correctly
**Issue**: ContactInfo title/phone number/email is not showing up the correct data. 

**Details**:
'contactInfo' section keeps showing "Reach out to me" and no data about phone number or email address. I can change the subtitle to anything else and it works just fine but not the title, phone number, email address, or lottie.
image

Here's the code I have from my portfolio.js
image

**Note**:
"Contact Me ☎️" and the appropriate Lottie/animation was showing up correctly but the Github portfolio was not showing up at all and no matter what I do using just the env file for adding my Github token didn't work and keep constantly showing FailedToLoad in the console. So, I was finally able to solve this issue by using the technique of 
`$env:REACT_APP_GITHUB_TOKEN = "my_unique_token"` in Powershell. Now the Github profile is showing up but not the contactInfo section. Any idea what's breaking this and where is this _"Reach out to me"_ coming from?
A production build can be found here with this issue: [https://rasam-hossain.github.io/](https://rasam-hossain.github.io/)

### PR DESCRIPTION
**Pull request by pktippa**
resolves #294

### CODE REVIEW

**Comment by kartikcho** [comment]
Hey @pktippa, this isn't a valid contribution as this doesn't fix any issue. Please take a look at the issues board before opening a PR!

**Comment by pktippa** [comment]
@kartikcho the PR actually solves issue #294 , please reverify the PR

**Review by saadpasta — CHANGES_REQUESTED** [review]
Please remove your info from .all-contributorsrc. We would handle that ourselves, everything else looks good to me

**Comment by kartikcho** [comment]
This change won't fix #294 though so this PR isn't necessary @saadpasta

**Comment by saadpasta** [comment]
@kartikcho Oh really sorry. I thought it was the issue with the key. Now I have read the Issue completely. Really sorry for the inconvenience. @pktippa Sorry this PR isn't a valid contribution.

**Pull request closed without merging**
