### PR TITLE
Issue #157 - Blog Card Layout

### PR DESCRIPTION
**Pull request by parasnagpal**
Hope this helps!!

### CODE REVIEW

**Comment by kartik918** [comment]
Also a good practice to follow, don't refer the issue in your PR title, it doesn't help anyone and it doesn't notify the issue either that it has a PR that will be closed when it gets merged. The maintainers don't remember the issues by their #number either, just use the issue title in your PR name and link it in the description like:
Fixes #157 

Hope this helps in your future contributions @parasnagpal !

**Comment by parasnagpal** [comment]
Thanks for pointing out my mistakes and suggesting improvements @kartik918  @saadpasta . This was my first pr.

**Comment by saadpasta** [comment]
@parasnagpal Great Work. Looking for more contributions from you. ❤️

**Comment by saadpasta** [comment]
@allcontributors add @parasnagpal for code

**Pull request merged**
