### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vandana1499**
Changed the sequence of the README.md . The license section is the last part of the README.md.

### CODE REVIEW

**Comment by kartikcho** [comment]
Hey @vandana1499 I appreciate the PR for this but you should comment on the issue you're working on first before submitting a PR for it. 
It's my bad I didn't assign @anshdhinhgra47 on it earlier but a heads up would've been great so 2 people aren't working on the same thing :)
@anshdhinhgra47 you can take this change off in your submitted PR!

**Review by kartikcho — APPROVED** [review]

**Comment by naveen521kk** [comment]
@all-contributors please add @vandana1499 for docs

**Comment by naveen521kk** [comment]
@kartikcho Looks like both the issues are different or I'm confused.

**Comment by kartikcho** [comment]
Rearrangement was a part of that issue, it's all sorted now :)

**Comment by anshdhinhgra47** [comment]
Wait, so I don't have to do anything now ?

**Pull request merged**
