### PR TITLE
feat: Serve next-gen images

### LINKED ISSUE #118: Serve images in next-gen formats
The images in the assets folder are in PNG or JPEG. Those images should be converted into next-gen formats like JPEG 2000, JPEG XR, or WebP for faster page loading time and improving the [PageSpeed score.](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdeveloperfolio.js.org%2F&tab=mobile)

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #118

### CODE REVIEW

**Comment by saadpasta** [comment]
@naveen521kk  @aashutoshrathi  we are not using that image try to remove the key from portfolio.js and check.

**Comment by naveen521kk** [comment]
@aashutoshrathi Remove it from the portfolio.

Also, @saadpasta why does it ask for authorization in Versel? Also, I couldn't authorize. Maybe you should add me I think.

**Comment by aashutoshrathi** [comment]
@saadpasta @naveen521kk Updated.

**Comment by naveen521kk** [comment]
@all-contributors please add @aashutoshrathi for Code

**Pull request merged**
