### PR TITLE
Changed screen capture GIF

### LINKED ISSUE #292: Update README with a new captured gif
Current screen captured gif is outdated and doesn't include many of the new additions since. A PR updating it would be a great first contribution for newcomers.

### PR DESCRIPTION
**Pull request by AlKun25**
Resolved #292 

- The screen capture GIF was changed and updated in README
  - Included GIF in both dark and light themes.

### CODE REVIEW

**Comment by saadpasta** [comment]
@AlKun25 Looks good. But just add a light theme gif only in Readme.md

**Review by saadpasta — COMMENTED** [review]
@AlKun25 Looks good. But just add a light theme gif only in Readme.md

**Comment by AlKun25** [comment]
Removed the dark-themed GIF, any more changes needed

**Review by saadpasta — APPROVED** [review]

**Comment by saadpasta** [comment]
@allcontributors please add @AlKun25 for doc

**Pull request merged**
