### PR TITLE
Add Progress Bar Component

### PR DESCRIPTION
**Pull request by kartik918**
Added a new progress bar component as was discussed in #39.
Shows user proficiency in certain skills.

Screenshot:

Screenshot (60)

### CODE REVIEW

**Comment by naveen521kk** [comment]
@kartik918 Have you added animation while the progress bar loads? The colour should fill when the user views that component.

**Comment by kartik918** [comment]
Addressed your feedback @saadpasta , now it appears if key is set to true.

**Comment by kartik918** [comment]
Naveen I have a plan for overhauling the app to have animations for every component to make it more interactive. Adding grow transitions right now in an app that is completely static in terms of transitions would make it look off. 
If you want to help out in making the app interactive, I'll help you get started in the right direction.

**Comment by naveen521kk** [comment]
@kartik918 I think that can be done but later. For now I am planning to make the Blog Component have latest posts from the RSS feed. Maybe you can add that as an Issue and lets solve it later.

**Pull request merged**
