### PR TITLE
Dockerized developerFolio

### PR DESCRIPTION
**Pull request by viveksharmaui**
Hello i have added a docker file in developerfolio now if someone clone this project they don't need to install node js version manually docker will do that .

Docker commands for building and running image .

BUILD IMAGE : `docker build -t developerfolio:latest .`
RUN IMAGE: `docker run -p 3000:3000 developerfolio:latest`

#slimcoder

### CODE REVIEW

**Comment by saadpasta** [comment]
@viveksharmaui Great Work. Can you please add a section in the Readme.md. So that user can know how to start it using docker.
Thanks 😀

**Comment by viveksharmaui** [comment]
Sure i will send PR for that .

**Comment by kartik918** [comment]
Can you update README setup guide with an additional commit under this PR for a more consistent code graph development tree? Thank you for your contribution!

**Comment by viveksharmaui** [comment]
@kartik918  thank you for communicated unfortunately i was unable to get where should i move hr please guide me or send me PR on my fork repo :)

**Comment by viveksharmaui** [comment]
@kartik918  i think you should merge this PR and update readme.md by yourself because updating readme.md is very boring work lol ! 

#slimcoder

**Comment by kartik918** [comment]
@viveksharmaui haha it's alright I fixed it. Good work !

**Comment by viveksharmaui** [comment]
@kartik918  why test is failed ?

**Comment by kartik918** [comment]
It's because of adding extra blank lines at some areas in the document, nothing serious.

**Comment by saadpasta** [comment]
@allcontributors add @viveksharmaui for code and doc

**Comment by saadpasta** [comment]
Good Work @viveksharmaui 😀

**Comment by viveksharmaui** [comment]
Thanks dude! get ready for some cool PR's from my side :)

**Pull request merged**
