### PR TITLE
:bug: fixed display option for StartupProject, Greeting, Talks and tw…

### PR DESCRIPTION
**Pull request by BourgeoisBenjamin**
Little fixed : display option for StartupProject, Greeting, Talks and twitter

A display verification has been added to StartupProject, Greeting, Talks and twitter containers

### CODE REVIEW

**Comment by saadpasta** [comment]
@BourgeoisBenjamin can you create an issue for the PR.

**Comment by BourgeoisBenjamin** [comment]
@saadpasta done. https://github.com/saadpasta/developerFolio/issues/296

**Review by saadpasta — APPROVED** [review]
LGTM ✌️

**Comment by saadpasta** [comment]
@allcontributors please add @BourgeoisBenjamin for code

**Pull request merged**
