### PR TITLE
Changed contact section styling

### PR DESCRIPTION
**Pull request by kartikch918**

### CODE REVIEW

**Comment by kartikch918** [comment]
I made it fit in with the clean minimal aesthetic of the page, also keeping it responsive for smaller screens.

Screenshot (47)

**Comment by kartikch918** [comment]
Github needs a confirmation dialog before accidentally closing PRs lol.

**Comment by kartikch918** [comment]
I made the new look fit in with the clean minimal aesthetic of the page. Also added simple hover transition to icons for a smooth experience.

Before:
Screenshot (49)

After:
Screenshot (47)

**Comment by saadpasta** [comment]
@kartikch918 Looks Good on Desktop can you send me the screenshot on how it looks Mobile. 
I think you should remove that Image on Small Devices that would look way better

Thanks For Contributing

**Comment by kartikch918** [comment]
It hides on smaller devices and has the same layout like before.

**Comment by kartikch918** [comment]
Screenshot (50)

**Comment by saadpasta** [comment]
@kartikch918 Good Work Thanks For Contributing

**Comment by saadpasta** [comment]
@allcontributors add @kartikch918 for code

**Comment by saadpasta** [comment]
@kartikch918 Great Work if you looking to contribute more make sure have a look at issue #20

**Pull request merged**
