### PR TITLE
Changed the email logo

### PR DESCRIPTION
**Pull request by SunitRoy2703**
changing the email logo to envelope, this will make it more clear for others to understand that the button is for email

### CODE REVIEW

**Review by kartikcho — APPROVED** [review]
LGTM, good catch!

**Comment by kartikcho** [comment]
@allcontributors please add @SunitRoy2703 for bug fixes

**Comment by SunitRoy2703** [comment]
Thank you so much!

**Comment by kartikcho** [comment]
I forgot to add you to the gang before 😅

**Pull request merged**
