### PR TITLE
Prettier version bump

### PR DESCRIPTION
**Pull request by kartikcho**
Fixed a formatting error in master, this should also fix the failing check in other PRs like #365.

### CODE REVIEW

**Comment by naveen521kk** [comment]
Hmm, why does CI fail here?

**Comment by kartikcho** [comment]
Okay I think I figured out what's wrong with the prettier checks, it's only looking at master everytime as mentioned in the workflow config.

Running the same check locally gives me green, so this is definitely checking the current state of master everytime which is failing as of now.

image

**Comment by naveen521kk** [comment]
> Okay I think I figured out what's wrong with the prettier checks, it's only looking at master everytime as mentioned in the workflow config.

Do you mean it checks out master each time it runs the checks (I mean the Github Action)?

**Comment by kartikcho** [comment]
Yes, master has formatting errors (which this PR addresses) and this is why formatting fails in every PR. And this action would also show green on PRs with formatting errors if the master is green.

**Comment by naveen521kk** [comment]
> Yes, master has formatting errors (which this PR addresses) and this is why formatting fails in every PR. And this action would also show green on PRs with formatting errors if the master is green.

No, I don't think so. It checks out this branch (see the logs https://github.com/saadpasta/developerFolio/pull/379/checks?check_run_id=2868560528#step:2:40) correctly. Maybe it's about the prettier version, CI install's `2.3.1` and in `package-lock.json` it is `2.3.0` https://github.com/saadpasta/developerFolio/blob/master/package-lock.json#L10977. Can you try updating and locally and then run `npm run format`?

**Comment by kartikcho** [comment]
Good catch, you're right, it was a result of version mismatch

**Comment by naveen521kk** [comment]
I think we should set up the depandabot to at least upgrade this.

**Review by naveen521kk — APPROVED** [review]
lgtm

**Pull request merged**
