### PR TITLE
Added Progress Bar-Pace

### PR DESCRIPTION
**Pull request by naveen521kk**
I have added a new progress bar to this site-Pace.
https://github.hubspot.com/pace/docs/welcome/

This is simple cdn linking of the pace.

### CODE REVIEW

**Comment by saadpasta** [comment]
@naveen521kk how will this help?

**Comment by naveen521kk** [comment]
This enhances the look and feel. I have seen many protofolio having a progress bar so I added one here.

**Comment by saadpasta** [comment]
> This enhances the look and feel. I have seen many protofolio having a progress bar so I added one here.

Can you please add a GIF or image on how it will look

**Comment by naveen521kk** [comment]
Here I have attached a gif on how it looks as well as the site is online at https://mknaveen.netlify.com/ .

https://i.ibb.co/dcRHT2Q/686214333d35f454cfe665a3d87d478a.gif

**Comment by saadpasta** [comment]
@naveen521kk Good Work 😀.  But I don't think it's necessary because it would distract the user

**Comment by naveen521kk** [comment]
Closing due to comments by @saadpasta

**Pull request closed without merging**
